Repository the-new-developers/tnd-website, pull requests merged in 2021-02, with the labels that each got.

#120 Fix filtering for featured event so that it shows on the main page
  website/src/pages/index.js
Labels: bug

#111 enhancement #110 move checkLink function
  website/src/common/check-link.js
  website/src/components/events/event-list-item.js
  website/src/templates/event-post.js
  website/src/templates/opportunities-post.js
Labels: enhancement

#121 Fix event post logic
  website/src/common/check-link.js
  website/src/pages/index.js
  website/src/templates/event-post.js
Labels: bug

#122 Fix post content not rendering
  website/src/templates/blog-post.js
  website/src/templates/event-post.js
  website/src/templates/opportunities-post.js
Labels: bug

#125 Create Events “s04e03-industry-mohawk-mixer”
  website/src/events/s04e03-industry-mohawk-mixer.md
Labels: netlify-cms/pending_publish
